# for `AWS` environment

services: 
  - name: fe-nginx
    replicaCount: 1
    revisionHistoryLimit: 3
    image:
      repository: jnuho/fe-nginx
      tag: "latest"
      #pullPolicy: IfNotPresent
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 8080
      targetPort: 80
    containerPort: 80
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 3
    volumes:
      - name: config-volume
        configMap:
          name: application-settings
    # Additional volumeMounts on the output Deployment definition.
    volumeMounts:
      - name: config-volume
        mountPath: /config

  - name: be-go
    #replicaCount: 1
    revisionHistoryLimit: 3
    image:
      repository: jnuho/be-go
      tag: "latest"
      #pullPolicy: IfNotPresent
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 3001
      targetPort: 3001
    containerPort: 3001
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
    readinessProbe:
      httpGet:
        path: /healthz-go
        port: 3001
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /healthz-go
        port: 3001
      initialDelaySeconds: 30
      periodSeconds: 10

  - name: be-py
    #replicaCount: 1
    revisionHistoryLimit: 3
    image:
      repository: jnuho/be-py
      tag: "latest"
      #pullPolicy: IfNotPresent
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 3002
      targetPort: 3002
    containerPort: 3002
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
    readinessProbe:
      httpGet:
        path: /healthz-py
        port: 3002
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /healthz-py
        port: 3002
      initialDelaySeconds: 30
      periodSeconds: 10


hpas:
  - name: fe-nginx-hpa
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 70
  - name: be-go-hpa
    minReplicas: 2
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 70
  - name: be-py-hpa
    minReplicas: 2
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 70


ingress:
  - name: fe-nginx-ingress
    className: "alb"
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      # alb.ingress.kubernetes.io/tags: Environment=prd,Team=devops
      # Default listen-ports:
      # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      # Default health check: / or /AWS.ALB/healthcheck
      # alb.ingress.kubernetes.io/healthcheck-path: /health
      #alb.ingress.kubernetes.io/security-groups: sg-02c6500ca5cf9bba6 # Add this annotation
    hosts:
      - http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fe-nginx-service
                port:
                  number: 8080
          - path: /web/cat
            pathType: Prefix
            backend:
              service:
                name: be-go-service
                port:
                  number: 3001
          - path: /weather
            pathType: Prefix
            backend:
              service:
                name: be-go-service
                port:
                  number: 3001
          - path: /healthz-go
            pathType: Prefix
            backend:
              service:
                name: be-go-service
                port:
                  number: 3001
          - path: /healthz-py
            pathType: Prefix
            backend:
              service:
                name: be-py-service
                port:
                  number: 3002
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

config:
  backend_go_url: http://k8s-default-fenginxi-ab0a71e16a-424716363.ap-northeast-2.elb.amazonaws.com
